apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: plexdrive
  labels:
    k8s-app: plexdrive
spec:
  selector:
    matchLabels:
      name: plexdrive
  template:
    metadata:
      labels:
        name: plexdrive
    spec:
      containers:
        - name: plexdrive
          image: "{{ .Values.images.container.repository }}:{{ .Values.images.container.tag }}"
          securityContext:
            privileged: true # Required for bidirectional mounting
          command: ["plexdrive"]
          args:
            {{- toYaml .Values.args | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","fusermount -uz /plexdrive"]
          startupProbe:
            exec:
              command:
              - cat
              - /plexdrive/health
            periodSeconds: 10
            failureThreshold: 300
          livenessProbe:
            exec:
              command:
              - cat
              - /plexdrive/health
            timeoutSeconds: 3
            failureThreshold: 8
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
