---
# Default values for plexdrive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
images:
  container:
    repository: wiserain/plexdrive
    tag: 5.2.1
  pullPolicy: IfNotPresent

# Note: livenessProbe and startupProbe rely on the existence
# of a "health" file in the root of your mount. Create a file for this purpose.

# Args hardcoded to start with mount and end with /plexdrive (VM mount point)
args:
  - mount
  - --config=/config/
  - --cache-file=/cache/cache.bolt
  - --uid=1000
  - --gid=1000
  - -o
  - allow_other
  # - --root-node-id=
  - -v2
  - /plexdrive
volumes:
  - name: media
    hostPath:
      path: /tmp/plexdrive
  - name: cache
    hostPath:
      path: /cache
      type: DirectoryOrCreate
  - name: config
    configMap:
      name: plexdrive-config
      items:
        - key: "config.json"
          path: "config.json"
        - key: "token.json"
          path: "token.json"


volumeMounts:
  - name: media
    mountPath: /plexdrive
    mountPropagation: Bidirectional
  - name: config
    mountPath: /config
    readOnly: true
  - name: cache
    mountPath: /cache


resources:
  limits:
    smarter-devices/fuse: 1
  requests:
    smarter-devices/fuse: 1
    cpu: 10m
    memory: 100Mi

nodeSelector: {}
  # plexdrive : enabled
