name: Manage versions

on:
  pull_request:
    paths:
      - 'charts/rclone'
      - '!charts/rclone/README.md'
      - '!charts/rclone/README.md.gotmpl'

jobs:
  bump:
    runs-on: ubuntu-latest
   
    steps:
      # Checkout action is required
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          scheme: semantic
          version-file: "{'path':'./charts/rclone/Chart.yaml', 'line':5}"
          files: >
            [
              "{'path':'./charts/rclone/Chart.yaml', 'line':5}"
            ] 
          rules: >
            [{
              "trigger": "pull-request",
              "destBranch": "main",
              "bump": "patch",
              "tag": false
            }]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
